### ISSUE TITLE
S3 source connector

### ISSUE THREAD

**Issue by radya13** [mmolimar/kafka-connect-fs#8]
Hi ! 
It s said  this connector supports S3 as source but in any way it is implemented in the code, Is there a way to add S3 source connector? 
Thank you

**Comment by mmolimar** [comment]
Hi there!
The connector implements the FileSystem abstraction provided by Hadoop. You just have to include your URI with the schema "s3://..." in the properties file and that should work :-)

By the way, you should include in that properties file:
policy.fs.fs.s3a.access.key=<ACCESS_KEY>
policy.fs.fs.s3a.secret.key=<SECRET_KEY>

**Comment by radya13** [comment]
Hi @mmolimar  ! 
Thank you for your quick answer , i ll try it today , the second question i miss understood, is, how can i run for example JDBC kafka connector( whose under confluent.../ ) and S3 connector  at the same time from the same server, is it possible?  and how to do so ?
Thank you

**Comment by mmolimar** [comment]
Sure you can. You can run it in standalone mode passing several connector properties files as args or even in distributed mode. Just read the [Confluent docs](https://docs.confluent.io/current/connect/userguide.html).

**Comment by lcalmeida** [comment]
Hi @mmolimar 
I'm trying to use the same feature but without success until now.
I just included my s3://bucket and the aws keys but when I start the connector I get the follow exception cause:
`java.io.IOException: No FileSystem for scheme: s3`

Do I need to add some dependency or use some specific file reader or policy?

Thank you!

**Comment by mmolimar** [comment]
I don't think so. You just have to package the connector with its dependencies and include them into the kafka-connect classpath.

**Comment by lcalmeida** [comment]
Thanks for the answer.
But I think there is something missing. I am using the latest kafka version (0.11.x)
I just package the master branch with `mvn clean package` and try to start the connector with the follow properties:

```
name=FsSourceConnector
connector.class=com.github.mmolimar.kafka.connect.fs.FsSourceConnector
tasks.max=1
topic=raw-file-transactions
fs.uris=s3://kafka-test-arquitetura/
policy.fs.fs.s3a.access.key=<my_key>
policy.fs.fs.s3a.secret.key=<my_sec_key>
policy.class=com.github.mmolimar.kafka.connect.fs.policy.SleepyPolicy
policy.sleepy.sleep=1000
policy.regexp=.*\.txt$
file_reader.class=com.github.mmolimar.kafka.connect.fs.file.reader.DelimitedTextFileReader
file_reader.delimited.token=,
file_reader.delimited.header=false
```

But with standard kafka libs I got the follow exception:
`Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration`

So I added some haddop libs according other exceptions like above happened:
I added the follow jars: (A lot, I know. Probably more than it needs)
```
hadoop-annotations-2.7.3.jar
hadoop-auth-2.7.3.jar
hadoop-client-2.7.3.jar
hadoop-common-2.7.3.jar
hadoop-hdfs-2.7.3.jar
hadoop-mapreduce-client-app-2.7.3.jar
hadoop-mapreduce-client-common-2.7.3.jar
hadoop-mapreduce-client-core-2.7.3.jar
hadoop-mapreduce-client-jobclient-2.7.3.jar
hadoop-mapreduce-client-shuffle-2.7.3.jar
hadoop-yarn-api-2.7.3.jar
hadoop-yarn-client-2.7.3.jar
hadoop-yarn-common-2.7.3.jar
hadoop-yarn-server-applicationhistoryservice-2.6.0.jar
hadoop-yarn-server-common-2.7.3.jar
hadoop-yarn-server-resourcemanager-2.6.0.jar
hadoop-yarn-server-web-proxy-2.6.0.jar
```

So I got the Exception:
`java.io.IOException: No FileSystem for scheme: s3`

I don't know if is so problem with the libs or kafka version. I figured out that it should be more simple that all my tries.
Do you think that the problem is because of a lib version?

**Comment by mmolimar** [comment]
Could you try with s3a or s3n FileSystem scheme? I mean:
fs.uris=s3a://<my_bucket>/

**Comment by lcalmeida** [comment]
Hi. I needed to change my tasks for now, so I have not completed the integration yet.
Thank you for your attention.
Just to register, with s3n the same problem occurred, but with s3a it seems to work correct because a correct class was instantiated. But another problem happened. When I come back to the implementation, I will try to solve this problem.

**Comment by mmolimar** [comment]
Great! You're welcome ;-)

**Comment by mceg** [comment]
Change hadoop version to 2.8.0 in pom.xml to get s3a working.However, I had to pass AWS credentails from env variables when I did that.

**Comment by mmolimar** [comment]
Cool then ;-)

**Comment by sanketgund07** [comment]
Hello, Please reply asap. I need to read data from S3 and need to send to kafka topic ie. S3 source connector, what changes i have to do here with this connector to achieve this. 

Thanks
