### ISSUE TITLE
you may get stale offsets value from context.offsetStorageReader() 

### ISSUE THREAD

**Issue by bearsiji** [mmolimar/kafka-connect-fs#9]
This project is awesome, I'd like to thank you at the first place.

I found that in each execution of poll() method, you get a FileReader relying on context.offsetStorageReader. However the offsetStorageReader only gives the committed offsets. And by default the offsets are only committed every 60 seconds (OFFSET_COMMIT_INTERVAL_MS_CONFIG).

https://github.com/mmolimar/kafka-connect-fs/blob/2ec3ec72b38c2724c4892b134b477f73747e9332/src/main/java/com/github/mmolimar/kafka/connect/fs/FsSourceTask.java#L74

This means in the current execution of poll(), you may return List<SourceRecord> with latest offsets, but in the next execution of poll(), you mostly get old values, since the offset hasn't been committed. (see org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter, org.apache.kafka.connect.runtime.OffsetStorageWriter, and org.apache.kafka.connect.runtime.WorkerSourceTask).

**Comment by bearsiji** [comment]
The comments of org.apache.kafka.connect.runtime.OffsetStorageWriter class says "Offset data should only be read during startup or reconfiguration of a task...", instead of being read in each execution of poll() method, I think.

**Comment by mmolimar** [comment]
Hi! Thanks for your comments.
Yes, you're right. In fact, that is documented [here](http://kafka-connect-fs.readthedocs.io/en/latest/connector.html#policies) and [here](http://kafka-connect-fs.readthedocs.io/en/latest/faq.html).

In order to avoid that issue you should take into account how to configure your policy based on your commit offset config.
